global:
    scrape_interval: 60s
    evaluation_interval: 60s

rule_files: []

scrape_configs:
    - job_name: autodelete
      static_configs:
        - targets: ["127.0.0.4:6136"]
          labels: {"shard": "6"}
        - targets: ["127.0.0.4:6137"]
          labels: {"shard": "7"}
        - targets: ["127.0.0.4:6138"]
          labels: {"shard": "8"}
        - targets: ["127.0.0.4:6139"]
          labels: {"shard": "9"}

